### PR TITLE
add connect and query methods test

### PR DESCRIPTION
**Pull request by marekfilip**
Change private methods to protected.
Move mysqli object creation to separate method.
Add phpunit to project.

thamaraiselvam/mysql-import#2

All methods were private and there is no way to test private methods. Had to change them to protected. Calling everything from contstructor makes it impossible to mock db so I had at least to separate creation of database connection to other method for further mocking.

There is still openfile method to test but you need to tell if my work is fine for this moment.

### CODE REVIEW

**Comment by marekfilip** [comment]
WORK IN PROGRESS

**Comment by thamaraiselvam** [comment]
Great work @marekfilip 👏🏼

**Comment by thamaraiselvam** [comment]
Let me know once you are done @marekfilip 

https://github.com/thamaraiselvam/mysql-import/pull/6 Travis CI is added, If possible add the unit test command in Travis CI as well.

**Comment by marekfilip** [comment]
Alright, I think it's ready, please review the code @thamaraiselvam 👍 
I think that someone need to develop more test cases for `testOpenfile` and `testOpenfileException` :) 

Unfortunately I hadn't better idea to test openfile method then just count runned queries.
Maybe someone will figure additional or better way to test it?

**Comment by thamaraiselvam** [comment]
It is a great PR @marekfilip 👏🏼 You are a champion.

- [ ] Currently, `PHPUnit 5.7.27` is installed and it is no longer supported. Can you please upgrade it to the latest version [php unit 8](https://phpunit.de/getting-started/phpunit-8.html)

- [ ] Add unit test command into Travis ci script.

**Comment by marekfilip** [comment]
I choosed PHPUnit 5 because it supports PHP 5.6 which is a requirement in composer.json. PHPUnit 8 supports PHP 7.2 and 7.3. Should I update the requirements in composer.json to php >= 7.2?

**Comment by thamaraiselvam** [comment]
Make sense, Let it be in version 5.

can you add phpunit script to travis ci

**Pull request merged**
